// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7uQ1zKSzlYAYkZh1PrXRL4_jStsrWJZ0',
    appId: '1:856131582275:web:4b62501a1f4ffb5a6117f6',
    messagingSenderId: '856131582275',
    projectId: 'bankam-d4c8f',
    authDomain: 'bankam-d4c8f.firebaseapp.com',
    storageBucket: 'bankam-d4c8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTeiWGN4-cLRqZVrSrg4SFdpuRaMq1TU',
    appId: '1:856131582275:android:559f43cbffaaddd76117f6',
    messagingSenderId: '856131582275',
    projectId: 'bankam-d4c8f',
    storageBucket: 'bankam-d4c8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBe7uhYUx0WAeYC2DSJqa4x_RJa-TLC0',
    appId: '1:856131582275:ios:0e0441da42422bbe6117f6',
    messagingSenderId: '856131582275',
    projectId: 'bankam-d4c8f',
    storageBucket: 'bankam-d4c8f.firebasestorage.app',
    iosBundleId: 'com.bankam.eykarBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBe7uhYUx0WAeYC2DSJqa4x_RJa-TLC0',
    appId: '1:856131582275:ios:0e0441da42422bbe6117f6',
    messagingSenderId: '856131582275',
    projectId: 'bankam-d4c8f',
    storageBucket: 'bankam-d4c8f.firebasestorage.app',
    iosBundleId: 'com.bankam.eykarBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7uQ1zKSzlYAYkZh1PrXRL4_jStsrWJZ0',
    appId: '1:856131582275:web:3ff0b91106d2f5646117f6',
    messagingSenderId: '856131582275',
    projectId: 'bankam-d4c8f',
    authDomain: 'bankam-d4c8f.firebaseapp.com',
    storageBucket: 'bankam-d4c8f.firebasestorage.app',
  );
}
